backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Data"
      name: "data"
      file: "content/test.md"
      fields:
        - label: "Navbar"
          name: "Navbar" 
          widget: list
          allow_add : false
          fields :
            - label: "NavHeader"
              name: "NavHeader"
              widget: string
            - label: "NavLinks"
              name: "NavLinks" 
              widget: list
              fields :
                - { label: "link", name: "link", widget: "string"}
