backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/data.md"
      fields:
        - { label: "hero_title", name: "hero_title", widget: "string"}
        - { label: "hero_description", name: "hero_description", widget: "string" }