backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Data"
      name: "data"
      file: "content/data.md"
      fields:
        - label: "Navbar"
          name: "Navbar" 
          widget: list
          fields :
            - { label: "NavHeader", name: "NavHeader", widget: "string"}