backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: Navbar
      name: Navbar
      widget: list
      fields:
        - label: NavHeader 
          name: NavHeader 
          widget: string
        - label: NavLinks
          name: NavLinks
          widget: list
          fields:
            - {label: Link, name: Link, widget: string}