backend:
   name: git-gateway
   branch: main
   base_url: https://netlify-cms.adrianub.vercel.app
media_folder: public/images
public_folder: images
collections:
   - name: 'Welcome Page'
     label: 'WelcomePage'
     files:
        - label: 'Home'
          name: 'home'
          file: 'content/data.md'
          fields:
            - { label: 'hero_title', name: 'hero_title', widget: 'string' }
            - {
                  label: 'hero_description',
                  name: 'hero_description',
                  widget: 'string',
               }
            - label: 'Navbar'
              name: 'navbar'
              widget: object
              fields:
                - { label: 'NavHeader', name: 'navHeader', widget: 'string' }
                - label: 'NavLinks'
                  name: 'navLinks'
                  widget: list
                  fields:
                      - label: 'link'
                        name: 'link'
                        widget: 'string'
            - label: 'HeroData'
              name: 'heroData'
              widget: object
              fields:
                - { label: 'toast', name: 'toast', widget: 'string' }
                - { label: 'mainLine1', name: 'mainLine1', widget: 'string' }
                - { label: 'mainLine2', name: 'mainLine2', widget: 'string' }
                - { label: 'tagLine', name: 'tagLine', widget: 'string' }
                - {
                      label: 'placeHolder',
                      name: 'placeHolder',
                      widget: 'string',
                  }
                - { label: 'btnTxt', name: 'btnTxt', widget: 'string' }
            - label: 'DetailsData'
              name: 'detailsData'
              widget : object
              fields :
                - { label : 'img', name: 'img', widget: 'string'}
                - { label : 'cashBack', name: 'cashBack', widget: 'string'}
                - { label : 'savings', name: 'savings', widget: 'string'}
                - { label : 'faster', name: 'faster', widget: 'string'}
                - { label : 'tagline', name: 'tagline', widget: 'string'}
                - { label : 'changingTxt', name: 'changingTxt', widget: 'string'}
                - label : 'cards'
                  name : 'cards'
                  widget : list
                  fields : 
                    - { label : 'icon', name: 'icon', widget: 'string'}
                    - { label : 'title', name: 'title', widget: 'string'}
                    - { label : 'text', name: 'text', widget: 'string'}
                - { label : 'playBtn', name: 'playBtn', widget: 'string'}
                - { label : 'playBtnTxt', name: 'playBtnTxt', widget: 'string'}
                - { label : 'footer', name: 'footer', widget: 'string'}
            - label : 'CustomersData'
              name : 'customersData'
              widget : object
              fields : 
                - { label : 'headline', name: 'headline', widget: 'string'}
                - label : 'customers'
                  name: 'customers'
                  widget: list
                  fields :
                    - { label : 'logo', name: 'logo', widget: 'string'}
            - label : 'ReviewData'
              name : 'reviewData'
              widget : object
              fields : 
                - { label : 'pic', name: 'pic', widget: 'string'}
                - { label : 'post', name: 'post', widget: 'string'}
                - { label : 'author', name: 'author', widget: 'string'}     
